[package]
name = "fabio-core"
version = "0.1.0"
edition = "2024"

[dependencies]
iana-time-zone = "0.1.65"
native-tls = "0.2.18"
postgres-native-tls = "0.5.3"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["rt"] }
tokio-postgres = "0.7.18"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
