[package]
name = "fabio"
version = "0.1.0"
description = "A fast, calm Postgres & SQLite client"
edition = "2024"

[lib]
# Distinct from the bin name, see https://github.com/rust-lang/cargo/issues/8519
name = "fabio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
fabio-core = { path = "../../crates/fabio-core" }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
